# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170616_1058'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='space',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='space',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='space',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='space',
            name='join_policy',
            field=models.CharField(choices=[('0', 'Invitation'), ('1', 'Free')], max_length=1, verbose_name='join policy'),
        ),
        migrations.AlterField(
            model_name='space',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
