# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='url',
            field=models.SlugField(),
        ),
    ]
