# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170616_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='polls.Question'),
        ),
    ]
