# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('assign', models.ManyToManyField(blank=True, to='profiles.Profile')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.Space')),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
    ]
