# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170526_1205'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
        migrations.AddField(
            model_name='task',
            name='assign',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
