# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170616_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ManyToManyField(blank=True, related_name='asignado', to='profiles.Profile'),
        ),
    ]
