# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170526_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
